export type Chassis = {
  id: string; brand: string; name: string; apps: string[]; category: number;
  summary: string; features: string; consideration: string; price?: number;
  priceNote?: string; url: string; history?: string; historyUrl?: string;
};
export const trucks = [
  { id: 'c63', name: '1963–1966 C10 / GMC', four: false },
  { id: 'c67', name: '1967–1972 C10 / GMC', four: false },
  { id: 'c73', name: '1973–1987 C10 / GMC', four: false },
  { id: 'k63', name: '1963–1966 K10', four: true },
  { id: 'k67', name: '1967–1972 K10', four: true },
  { id: 'k73', name: '1973–1980 K10', four: true },
  { id: 'k81', name: '1981–1987 K10', four: true },
  { id: 'k20', name: '1963–1987 K20 (4×4)', four: true },
  { id: 'b69', name: '1969–1972 K5 Blazer 4×4', four: true },
];
const c = ['c63','c67','c73'];
const k = ['k63','k67','k73','k81','k20'];
const tci = 'https://totalcostinvolved.com/product/';
const rs = 'https://roadstershop.com/product/';
export const chassis: Chassis[] = [
  { id:'tci-classic',brand:'TCI Engineering',name:'Classic',apps:['c67'],category:0,price:18695,summary:'A coilover foundation for cruising, everyday use and a lowered stance.',features:'Fully boxed frame · Pro-Touring IFS · adjustable four-link rear · Ridetech coilovers · four-wheel disc brakes',consideration:'Base mounts are for a small-block and automatic. Confirm drivetrain mounts and rear differential options. This product page specifies 1967–1972 despite its broader URL.',url:tci+'1963-1987-chevy-c10-truck-classic-chassis/' },
  { id:'tci-grounded',brand:'TCI Engineering',name:'Grounded',apps:['c67'],category:0,price:20595,summary:'Air suspension for a low parked stance and adjustable driving height.',features:'Front and rear airbags · Ridetech shocks · four-link rear · Currie 9-inch · disc brakes',consideration:'Air management is extra. Confirm body clearance and drivetrain compatibility for the selected stance.',url:tci+'1963-1987-chevy-c10-truck-grounded-chassis/' },
  { id:'tci-touring',brand:'TCI Engineering',name:'Pro-Touring',apps:['c67'],category:1,price:20595,summary:'Street comfort with suspension adjustability for handling-focused builds.',features:'Torque-arm rear · Ridetech coilovers · adjustable front alignment · power rack · disc brakes',consideration:'Rear sway bar, differential and brake upgrades affect the finished package price. Confirm body and tire clearance.',url:tci+'1963-1987-chevy-c10-truck-pro-touring-chassis/' },
  { id:'speedtech-ta',brand:'Speedtech Performance',name:'ExtReme Torque Arm',apps:['c67'],category:1,summary:'Designed for street driving, autocross and track days.',features:'Torque-arm rear · QA1 or JRi coilover choices · Sweet power rack · up to 315 mm front tires (manufacturer claim)',consideration:'Bed-floor modifications required. Confirm shocks, brakes and rear-end contents in the quote; the online FAQ mixes torque-arm and IRS specifications.',url:'https://speedtechperformance.com/67-72-gm-truck-extreme-chassis/' },
  { id:'speedtech-irs',brand:'Speedtech Performance',name:'ExtReme IRS',apps:['c67'],category:1,summary:'Independent rear suspension for a street-and-track build with more rear suspension tuning.',features:'Independent rear suspension · Sweet power rack · coilover options · up to 315 mm front / 355 mm rear tires (manufacturer claim)',consideration:'Floor and tunnel modifications required. Sheet-metal kits are available; confirm shocks and brakes in the configured quote.',url:'https://speedtechperformance.com/products/1967-1972-gm-truck-extreme-irs-chassis/' },
  ...(['c67','c73'] as const).flatMap(app => [
    { id:'rs-spec-'+app,brand:'Roadster Shop',name:'SPEC',apps:[app],category:0,price:15495,summary:'A street-oriented chassis with standard and lowered configurations.',features:'SPEC independent front suspension · parallel four-bar rear · power rack · Ford 9-inch housing',consideration:'Standard and Slammed packages have different body-clearance requirements. Slammed versions need bed/body modifications; brakes and gearing are configured separately.',url:rs+(app==='c67'?'1967-72-c10-standard/':'1973-87-c10-slammed/') },
    { id:'rs-fast-'+app,brand:'Roadster Shop',name:'FAST TRACK',apps:[app],category:1,price:22695,summary:'Pro-touring suspension with alignment settings for both street and track use.',features:'FAST TRACK front suspension · splined sway bar · four-bar rear · optional IRS',consideration:'Confirm bed, inner-fender and tire-clearance work for your application. Brakes, gearing and IRS change the package price.',url:rs+(app==='c67'?'1967-72-c10-fast-track/':'1973-87-c10/') },
  ]),
  { id:'rs-revo',brand:'Roadster Shop',name:'REVO',apps:['c67'],category:0,price:19995,summary:'A compact front-suspension design emphasizing comfortable street handling.',features:'REVO IFS · 5.5-inch front wheel travel (manufacturer claim) · parallel four-bar rear · Ford 9-inch housing',consideration:'Confirm current shock specification and brake package when quoting; the page lists multiple shock descriptions.',url:rs+'1967-72-c10/' },
  { id:'rs-rideline',brand:'Roadster Shop',name:'RideLine',apps:['c67'],category:0,price:26995,summary:'For drivers who put a smooth ride and reduced road noise first.',features:'Sealed control-arm bushings · longer suspension travel · Fox coilovers · Fast Link rear suspension',consideration:'Comfort-focused configuration. Confirm brakes, gearing, mounts and body-clearance requirements with the manufacturer.',url:rs+'1967-72-c10-3/' },
  { id:'nolimit',brand:'No Limit Engineering',name:'Pro-Tech',apps:c,category:1,summary:'A configurable street-and-track platform, with street-focused packages available too.',features:'Wide Ride IFS · four-link rear · coilover or air options · optional IRS and floating rear axle',consideration:'Standard rails are described as requiring no body or bed changes. Raised rails require raising the bed 4–5 inches and may require tunnel work. Confirm exact year and bed length.',url:'https://nolimit.net/store/Pro-Tech-Chassis-p26244635' },
  { id:'revb',brand:'RevB Chassis Company',name:'Air Ride Chassis',apps:c,category:0,price:18495,priceNote:'Starting price supplied by AZ Sport Trucks; confirm your package with RevB.',summary:'An air-suspension option for a custom street truck.',features:'Dominator airbags · JRI adjustable shocks · triangulated four-link · power rack · 9-inch housing and axles',consideration:'Brakes, third member, sway bars and fuel system are additional options. Confirm air management and assembly requirements.',url:'https://revbchassis.com/pages/get-a-quote' },
  { id:'artmorrison',brand:'Art Morrison',name:'GT Sport',apps:['c67'],category:0,summary:'A lowered street-performance foundation emphasizing ride quality and handling.',features:'Vehicle-specific GT Sport chassis · published C10 installation instructions · configurable suspension packages',consideration:'Exact builder package and price need a manufacturer quote. Confirm suspension choice, included equipment and transmission clearance.',url:'https://artmorrison.com/products/gt-sport-trucks/',history:'This C10 model is documented in the manufacturer’s 2023 catalog. This is not a verified launch date.',historyUrl:'https://artmorrison.com/wp-content/uploads/AME_Catalog2023.pdf' },
  { id:'schwartz',brand:'Schwartz Performance',name:'C10 Full Chassis',apps:['c67'],category:1,summary:'A short-bed chassis designed for comfortable street use and autocross or road-course driving.',features:'Adjustable Ridetech shock options · multiple brake packages · solid axle or IRS options',consideration:'Short-bed application. Base price excludes brakes, shocks and rear end. Some transmissions need floor changes; wide rear tires need mini-tubs.',url:'https://www.schwartzperformance.com/chassis/1967-1972-chevy-c10-gmc/',history:'Manufacturer product page dated July 12, 2018. The current version’s launch date is not confirmed.',historyUrl:'https://www.schwartzperformance.com/chassis/1967-1972-chevy-c10-gmc/' },
  { id:'cbc',brand:'CB Chassis Products',name:'Performance Chassis',apps:['c63','c67'],category:0,price:12325,priceNote:'Starting price supplied by AZ Sport Trucks; confirm selected equipment with CBC.',summary:'A lowered street chassis with adjustable rear suspension geometry.',features:'Triangulated four-link · rack-and-pinion steering · stated 5-inch ride height',consideration:'Ships unassembled in raw steel. Finishing and assembly are required. Coilovers, third member, sway bar and fuel tank are listed as additional options.',url:'https://cbcpro.com/collections/chassis/products/c10-performance-chassis-60-72' },
  { id:'finch',brand:'Finch Performance',name:'Apex Predator',apps:c,category:2,summary:'A candidate for a competition-led build, with documented street-and-track customer trucks.',features:'DSE-based front suspension · custom rear link arrangement · configurable shocks and brakes',consideration:'Current ordering availability, exact fitment and package contents need confirmation. Competition results depend on the complete truck and driver.',url:'https://www.finchperformance.com/',history:'Forgeline documents JB Granger’s C10 with an Apex Predator chassis. This supports a real-world build, not a chassis-only performance rating.',historyUrl:'https://www.forgeline.com/pages/vehicle-gallery/gallery-2589' },
  ...(['air','coil'] as const).map(type => ({ id:'gsi-'+type,brand:'GSI Machine & Fabrication',name:type==='air'?'Air Ride Chassis':'Coilover Chassis',apps:['c67'],category:type==='air'?0:1,price:type==='air'?18500:19500,summary:type==='air'?'Designed to lay frame with air suspension and modern street manners.':'A low coilover setup described for autocross, pro-touring and street use.',features:(type==='air'?'Front and rear airbags with shocks':'Front and rear Ridetech coilovers')+' · four-link rear · Watt’s link · power rack',consideration:'Axles, third member, brakes, sway bars and fuel tank are additional options. Confirm bed modifications and air management where applicable. Built-to-order quote required.',url:'https://www.gsimfab.com/products/67-72-c10-'+(type==='air'?'air-ride':'coil-over')+'-chassis' })),
  { id:'fatfender',brand:'Fat Fender Garage',name:'Custom Chassis',apps:c,category:0,summary:'Daily-driving and highway-cruising packages with a choice of stance.',features:'Level 1: 1–2-inch coilover drop · Level 2: 4–6-inch coilover drop · Level 3: frame-laying airbags',consideration:'Levels 2 and 3 require bed modifications. Exact application and included brakes, suspension and drivetrain depend on the quote.',url:'https://fatfender.com/products/chassis-builder' },
  ...(['coil','air'] as const).map(type=>({id:'scotts-'+type,brand:'Scott’s Hotrods',name:type==='coil'?'Coilover Chassis':'SuperSlam',apps:['c67'],category:0,price:type==='coil'?14750:15650,summary:type==='coil'?'Built to order around your drivetrain, wheels and preferred street stance.':'An airbag chassis for a frame-laying street build.',features:'Scott’s IFS · parallel four-bar rear · Moser 9-inch housing and axles · TIG-welded frame',consideration:'Brakes, third member, engine/transmission mounts and power steering cost extra. Long-bed option adds cost; low configurations require body modifications.',url:'https://scottshotrods.com/1963-87-chevy-gmc-chassis/'})),
  ...(['pickup','blazer'] as const).flatMap(body=>[
    {id:'tci-pro-'+body,brand:'TCI Engineering',name:'Pro 4×4',apps:body==='pickup'?k:['b69'],category:1,price:42995,summary:'A four-link 4×4 platform for highway miles and trail use.',features:'Currie 44 front / 60 rear · Fox remote-reservoir coilovers · adjustable anti-sway bars · claimed 12-inch wheel travel front/rear',consideration:'Designed around LS/LT powertrains and a driver-side-output Atlas transfer case. PRO2/PRO3 upgrades, fuel tank and finish add cost.',url:tci+(body==='pickup'?'1963-1987-k10-pro1-4x4-chassis/':'1969-1972-chevy-k5-blazer-4x4-chassis/')},
    {id:'tci-extreme-'+body,brand:'TCI Engineering',name:'Pro-Extreme 4×4',apps:body==='pickup'?k:['b69'],category:2,price:50995,summary:'A heavier-duty axle package designed for demanding off-road terrain.',features:'Currie Extreme 60 one-ton axles · 40-spline full-floating rear · eight-lug hubs · Fox coilovers',consideration:'Requires compatible eight-lug wheels. LS/LT and driver-side-output Atlas packaging; confirm drivetrain, gearing and finished package contents.',url:tci+(body==='pickup'?'1963-1987-chevy-k10-k20-pro-extreme-4x4-chassis/':'1969-1972-chevy-k5-blazer-pro-extreme-4x4-chassis-with-1-ton-axles-new/')},
    {id:'rs-legend-'+body,brand:'Roadster Shop',name:'Legend Series',apps:body==='pickup'?['k73']:['b69'],category:0,summary:'Modern OEM suspension components with an emphasis on road comfort and serviceability.',features:'GM independent front suspension · Fox front coilovers · rear leaf springs · GM brakes',consideration:'Pickup listing covers K10, not confirmed for K20. Overview and product-page pricing differ substantially; request a current package quote.',url:rs+(body==='pickup'?'1973-80-k10-legend-series-chassis/':'1969-72-blazer-legend-series-chassis/')},
    {id:'rs-rs4-'+body,brand:'Roadster Shop',name:'RS4',apps:body==='pickup'?['k73','k81']:['b69'],category:1,price:44995,summary:'Linked solid axles and coilovers for road and off-road use.',features:'Currie Dana 44 front / Dana 60 rear · front and rear links · Fox coilovers',consideration:'Pickup listing covers K10, not confirmed for K20. Published travel and package details differ between overview and product page; confirm configuration.',url:rs+(body==='pickup'?'1973-87-k10/':'1969-72-blazer/')},
  ]),
  {id:'scotts-apex',brand:'Scott’s Hotrods',name:'ApeX4',apps:[...k,'b69'],category:1,price:39332,summary:'A built-to-order 4×4 platform for street driving and demanding trails.',features:'Moser housings and 35-spline axles · full-floating rear · four-links · Fox remote-reservoir coilovers',consideration:'Exact model/year fitment requires manufacturer confirmation. Brakes, third members, sway bars, mounts and plumbing are upgrades. Published 10-inch figure is shock travel.',url:'https://scottshotrods.com/apex4-chassis/'},
];
